runtime: nodejs16

instance_class: F2

handlers:
  - url: /_nuxt
    static_dir: dist/_nuxt
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt|mp4))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt|mp4)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'